FROM python:3.9.0-alpine3.12

WORKDIR /usr/src/app

COPY requirements.txt ./

# https://github.com/psycopg/psycopg2/issues/684#issuecomment-392015532
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "-m", "monitoring.worker"]